USE ReportingDB
GO

/****** Object:  Table [ref].[AccountType]    Script Date: 4/18/2019 4:36:46 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

drop table DBO.[BANK_ACCOUNT_TYPE_DIM]
CREATE TABLE DBO.[BANK_ACCOUNT_TYPE_DIM](
	[BANK_ACCOUNT_TYPE_DIM_KEY] [INT]  IDENTITY(10000,1), 
	[BANK_ACCOUNT_TYPE_CODE] AS   [BANK_ACCOUNT_TYPE_DIM_KEY] - 9990, 
	[BANK_ACCOUNT_TYPE_GUID] [uniqueidentifier] NOT NULL,
	[BANK_ACCOUNT_TYPE_NAME] [varchar](100) NULL,
	[BANK_ACCOUNT_TYPE_DESC] [varchar](max) NULL,
	[ISACTIVE] [bit] NOT NULL,
	[CREATEDDATE] [date] NOT NULL,
	[MODIFIEDDATE] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[BANK_ACCOUNT_TYPE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


Insert into DBO.[BANK_ACCOUNT_TYPE_DIM]
([BANK_ACCOUNT_TYPE_GUID],[BANK_ACCOUNT_TYPE_NAME] ,[BANK_ACCOUNT_TYPE_DESC] ,[ISACTIVE]   ,[CREATEDDATE]  ,[MODIFIEDDATE])
SELECT A.id,A.[Name]
      , A.[Description]
      , A.[IsActive]
      , A.[CreatedDate]
      , A.[ModifiedDate]
  FROM [THM].[ref].[AccountType] a
  left JOIN
	DBO.[BANK_ACCOUNT_TYPE_DIM] B
	On a.Name = B.[BANK_ACCOUNT_TYPE_NAME] and a.id = b.[BANK_ACCOUNT_TYPE_GUID]
where B.[BANK_ACCOUNT_TYPE_NAME] IS NULL and b.[BANK_ACCOUNT_TYPE_GUID] is null


--Select top 1 * from DBO.[BANK_ACCOUNT_TYPE_DIM]

------------------------------------------------------------
drop table DBO.[ACTOR_TYPE_DIM]
CREATE TABLE DBO.[ACTOR_TYPE_DIM](
	[ACTOR_TYPE_DIM_KEY] [INT]  IDENTITY(10000,1),
	[ACTOR_TYPE_CODE] AS   [ACTOR_TYPE_DIM_KEY] - 9990, 
	[ACTOR_TYPE_GUID] [uniqueidentifier] NOT NULL,
	[ACTOR_TYPE_NAME] [varchar](100) NULL,
	[ACTOR_TYPE_DESC] [varchar](max) NULL,
	[ISACTIVE] [bit] NOT NULL,
	[CREATEDDATE] [date] NOT NULL,
	[MODIFIEDDATE] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ACTOR_TYPE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


Insert into DBO.ACTOR_TYPE_DIM
( [ACTOR_TYPE_GUID],[ACTOR_TYPE_NAME], [ACTOR_TYPE_DESC], [ISACTIVE],  [CREATEDDATE], [MODIFIEDDATE])
SELECT A.ID,A.[Name]
      ,A.[Description]
      ,A.[IsActive]
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].[ActorType] A
   left JOIN
	DBO.ACTOR_TYPE_DIM B
	On a.Name = B.[ACTOR_TYPE_NAME] and a.id = b.[ACTOR_TYPE_GUID]
where B.[ACTOR_TYPE_NAME] IS NULL and b.[ACTOR_TYPE_GUID] is null


--Select top 1 * from DBO.ACTOR_TYPE_DIM



----------------------------------------------------------------
drop table DBO.[ADDRESS_TYPE_DIM]
CREATE TABLE DBO.[ADDRESS_TYPE_DIM](
	[ADDRESS_TYPE_DIM_KEY] [INT]  IDENTITY(10000,1), 
	[ADDRESS_TYPE_CODE] AS   [ADDRESS_TYPE_DIM_KEY] - 9990, 
	[AADDRESS_TYPE_GUID] [uniqueidentifier] NOT NULL,
	[ADDRESS_TYPE_NAME] [varchar](100) NULL,
	[ADDRESS_TYPE_DESC] [varchar](max) NULL,
	[ISACTIVE] [bit] NOT NULL,
	[CREATEDDATE] [date] NOT NULL,
	[MODIFIEDDATE] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ADDRESS_TYPE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


Insert into DBO.[ADDRESS_TYPE_DIM]
( [AADDRESS_TYPE_GUID],[ADDRESS_TYPE_NAME], [ADDRESS_TYPE_DESC], [ISACTIVE],  [CREATEDDATE], [MODIFIEDDATE])
SELECT a.id,A.[Name]
      ,A.[Description]
      ,A.[IsActive]
       ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].[AddressType] A
   left JOIN
	DBO.[ADDRESS_TYPE_DIM] B
	On a.Name = B.[ADDRESS_TYPE_NAME] and a.id = b.[AADDRESS_TYPE_GUID]
where B.[ADDRESS_TYPE_NAME] IS NULL and b.[AADDRESS_TYPE_GUID] is null


--Select top 1 * from DBO.[ADDRESS_TYPE_DIM]


--------------------------------------
drop table DBO.[BODY_GROUP_DIM]
CREATE TABLE DBO.[BODY_GROUP_DIM](
	[BODY_GROUP_DIM_KEY] [INT]  IDENTITY(10000,1), 
	[BODY_GROUP_CODE] AS   [BODY_GROUP_DIM_KEY] - 9990, 
	[BODY_GROUP_GUID] [uniqueidentifier] NOT NULL, 
	[BODY_GROUP_NAME] [varchar](100) NULL,
	[BODY_GROUPDESC] [varchar](max) NULL,
	[ISACTIVE] [bit] NOT NULL,
	[CREATEDDATE] [date] NOT NULL,
	[MODIFIEDDATE] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[BODY_GROUP_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


Insert into DBO.[BODY_GROUP_DIM]
(  [BODY_GROUP_GUID],[BODY_GROUP_NAME], [BODY_GROUPDESC], [ISACTIVE],  [CREATEDDATE], [MODIFIEDDATE])
SELECT a.id,A.[Name]
      ,A.[Description]
      ,A.[IsActive]
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].[BodyGroup] A
   left JOIN
	DBO.[BODY_GROUP_DIM] B
	On a.Name = B.[BODY_GROUP_NAME] and a.id = b.[BODY_GROUP_GUID]
where B.[BODY_GROUP_NAME] IS NULL and b.[BODY_GROUP_GUID] is null


--Select top 1 * from DBO.[BODY_GROUP_DIM]


--------------------------------------
drop table DBO.[BODY_GROUP_PART_DIM]
CREATE TABLE DBO.[BODY_GROUP_PART_DIM](
	[BODY_GROUP_PART_DIM_KEY] [INT]  IDENTITY(10000,1), 
	[BODY_GROUP_PART_CODE] AS   [BODY_GROUP_PART_DIM_KEY] - 9990, 
	[BODY_GROUP_PART_GUID] [uniqueidentifier] NOT NULL,  
	[BODY_GROUP_PART_NAME] [varchar](100) NULL,
	[BODY_GROUP_PART_DESC] [varchar](max) NULL,
	[ISACTIVE] [bit] NOT NULL,
	[CREATEDDATE] [date] NOT NULL,
	[MODIFIEDDATE] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[BODY_GROUP_PART_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


Insert into DBO.[BODY_GROUP_PART_DIM]
(  [BODY_GROUP_PART_GUID],[BODY_GROUP_PART_NAME], [BODY_GROUP_PART_DESC], [ISACTIVE],  [CREATEDDATE], [MODIFIEDDATE])
SELECT BP.ID,BG.[Name]
      ,BP.[Name]
      ,BP.[IsActive]
      ,BP.[CreatedDate]
      ,BP.[ModifiedDate]
  FROM [THM].[ref].[BodyPart] BP join [THM].[ref].[BodyGroup] BG on bg.id = bp.BodyGroupId
   left JOIN
	DBO.[BODY_GROUP_PART_DIM] B
	On BG.Name = B.[BODY_GROUP_PART_NAME] and BP.Name= B.[BODY_GROUP_PART_DESC] and BP.ID = B.[BODY_GROUP_PART_GUID]
where B.[BODY_GROUP_PART_NAME] IS NULL and B.[BODY_GROUP_PART_DESC] is null and B.[BODY_GROUP_PART_GUID] is null 
 order by bg.Name

--Select top 1 * from DBO.[BODY_GROUP_PART_DIM]




--------------------------------------------------------------------

drop table DBO.[BODY_SIDE_DIM]

CREATE TABLE DBO.[BODY_SIDE_DIM](
	[BODY_SIDE_DIM_KEY] [INT]  IDENTITY(10000,1), 
	[BODY_SIDE_CODE] AS   [BODY_SIDE_DIM_KEY] - 9990,
	[BODY_SIDE_GUID] [uniqueidentifier] NOT NULL,    
	[BODY_SIDE_NAME] [varchar](100) NULL,
	[BODY_SIDE_DESC] [varchar](max) NULL,
	[ISACTIVE] [bit] NOT NULL,
	[CREATEDDATE] [date] NOT NULL,
	[MODIFIEDDATE] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[BODY_SIDE_DIM_KEY]  ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


Insert into DBO.[BODY_SIDE_DIM]
( [BODY_SIDE_GUID],[BODY_SIDE_NAME], [BODY_SIDE_DESC], [ISACTIVE],   [CREATEDDATE], [MODIFIEDDATE])
SELECT A.ID,A.[Name]
      ,A.[Description]
      ,A.[IsActive]
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].[BodySide] A
   left JOIN
	DBO.[BODY_SIDE_DIM] B
	On a.Name = B.[BODY_SIDE_NAME] and A.id = B.[BODY_SIDE_GUID]
where B.[BODY_SIDE_NAME] IS NULL and B.[BODY_SIDE_GUID] is NULL


--Select top 1 * from DBO.[BODY_SIDE_DIM]


--------------------------------------
drop table DBO.[BODY_GROUP_PART_SIDE_DIM]
CREATE TABLE DBO.[BODY_GROUP_PART_SIDE_DIM](
	[BODY_GROUP_PART_SIDE_DIM_KEY] [INT]  IDENTITY(10000,1), 
	[BODY_GROUP_PART_SIDE_CODE] AS   [BODY_GROUP_PART_SIDE_DIM_KEY] - 9990,
	[BODY_GROUP_PART_SIDE_GUID] [uniqueidentifier] NOT NULL,    
	[BODY_GROUP_PART_SIDE_GROUP_NAME] [varchar](100) NULL,
	[BODY_GROUP_PART_SIDE_NAME] [varchar](100) NULL,
	[BODY_GROUP_PART_SIDE_DESC] [varchar](max) NULL,
	[ISACTIVE] [bit] NOT NULL,
	[CREATEDDATE] [date] NOT NULL,
	[MODIFIEDDATE] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[BODY_GROUP_PART_SIDE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


Insert into DBO.[BODY_GROUP_PART_SIDE_DIM]
( [BODY_GROUP_PART_SIDE_GUID], [BODY_GROUP_PART_SIDE_GROUP_NAME], [BODY_GROUP_PART_SIDE_NAME],[BODY_GROUP_PART_SIDE_DESC] ,[ISACTIVE],  [CREATEDDATE], [MODIFIEDDATE])
SELECT BP.ID,BG.[Name] BodyGroup
      ,BP.[Name] bodypart
	  ,bs.name as body_part
      ,BP.[IsActive]
      ,BP.[CreatedDate]
      ,BP.[ModifiedDate]
  FROM [THM].[ref].[BodyPart] BP join [THM].[ref].[BodyGroup] BG on bg.id = bp.BodyGroupId
    join [THM].[ref].BodyPartSideMap bps on bps.BodyPartId = bp.id 
  join [THM].[ref].BodySide bs on bs.id = bps.BodySideId
   left JOIN
	DBO.[BODY_GROUP_PART_SIDE_DIM] B
	On BG.Name = B.[BODY_GROUP_PART_SIDE_GROUP_NAME] and BP.Name= B.[BODY_GROUP_PART_SIDE_NAME] and bs.name = B.[BODY_GROUP_PART_SIDE_DESC]
	and BP.id = B.[BODY_GROUP_PART_SIDE_GUID]
where B.[BODY_GROUP_PART_SIDE_GROUP_NAME] IS NULL and B.[BODY_GROUP_PART_SIDE_NAME] is null and B.[BODY_GROUP_PART_SIDE_DESC] is null
and B.[BODY_GROUP_PART_SIDE_GUID] is null
  order by bg.Name,bp.name,bs.name

--Select top 1 * from DBO.[BODY_GROUP_PART_SIDE_DIM]

-------------------------------------------------------
drop table DBO.[CLIENT_TYPE_DIM]
CREATE TABLE DBO.[CLIENT_TYPE_DIM](
	[CLIENT_TYPE_DIM_KEY] [INT]  IDENTITY(10000,1),
	[CLIENT_TYPE_CODE] AS   [CLIENT_TYPE_DIM_KEY] - 9990,
	[CLIENT_TYPE_GUID] [uniqueidentifier] NOT NULL,     
	[CLIENT_TYPE_NAME] [varchar](100) NULL,
	[ISACTIVE] [bit] NOT NULL,
	[CREATEDDATE] [date] NOT NULL,
	[MODIFIEDDATE] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[CLIENT_TYPE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO

Insert into DBO.[CLIENT_TYPE_DIM]
( [CLIENT_TYPE_GUID],[CLIENT_TYPE_NAME],  [ISACTIVE],   [CREATEDDATE], [MODIFIEDDATE])
SELECT A.id,A.[Name]
      ,A.[IsActive]
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].ClientType A
   left JOIN
	DBO.[CLIENT_TYPE_DIM] B
	On a.Name = B.[CLIENT_TYPE_NAME] and a.id = B.[CLIENT_TYPE_GUID]
where B.[CLIENT_TYPE_NAME] IS NULL and B.[CLIENT_TYPE_GUID] is null


--Select top 1 * from DBO.[CLIENT_TYPE_DIM]


----------------------------------------------------------
drop table [DBO].[CONTACT_TYPE_DIM]

CREATE TABLE [DBO].[CONTACT_TYPE_DIM](
	[CONTACT_TYPE_DIM_KEY] [INT]  IDENTITY(10000,1), 
	[CONTACT_TYPE_CODE] AS   [CONTACT_TYPE_DIM_KEY] - 9990, 
	[CONTACT_TYPE_GUID] [uniqueidentifier] NOT NULL,     
	[CONTACT_TYPE_NAME] [VARCHAR](100) NULL,
	[CONTACT_TYPE_DESC] [VARCHAR](MAX) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[CREATEDDATE] [date] NOT NULL,
	[MODIFIEDDATE] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[CONTACT_TYPE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

Insert into DBO.[CONTACT_TYPE_DIM]
( [CONTACT_TYPE_GUID],[CONTACT_TYPE_NAME], [CONTACT_TYPE_DESC], [ISACTIVE],   [CREATEDDATE], [MODIFIEDDATE])
SELECT A.id, A.[Name]
	  ,A.Description
      ,A.[IsActive]
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].ContactType A
   left JOIN
	DBO.[CONTACT_TYPE_DIM] B
	On a.Name = B.[CONTACT_TYPE_NAME] and a.id = B.[CONTACT_TYPE_GUID]
where B.[CONTACT_TYPE_NAME] IS NULL and B.[CONTACT_TYPE_GUID] is null


--Select top 1 * from DBO.[CONTACT_TYPE_DIM]


------------------------------------
drop table [DBO].[DIAGNOSIS_DIM]
CREATE TABLE [DBO].[DIAGNOSIS_DIM](
	[DIAGNOSIS_DIM_KEY] [INT]  IDENTITY(10000,1), 
	[DIAGNOSIS_CODE] AS   [DIAGNOSIS_DIM_KEY] - 9990, 
	[DIAGNOSIS_GUID] [uniqueidentifier] NOT NULL,   
	[DIAGNOSIS_NAME] [VARCHAR](50) NOT NULL,
	[DIAGNOSIS_DESC] [VARCHAR](MAX) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[EFFECTIVEDATE] [date] NULL,
	[EXPIRATIONDATE] [date] NULL,
	[CREATEDDATE] [date] NULL,
	[MODIFIEDDATE] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[DIAGNOSIS_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


Insert into DBO.[DIAGNOSIS_DIM]
( [DIAGNOSIS_GUID],[DIAGNOSIS_NAME], [DIAGNOSIS_DESC], [ISACTIVE], [EFFECTIVEDATE], [EXPIRATIONDATE], [CREATEDDATE], [MODIFIEDDATE])
SELECT A.id,A.[Name]
	  ,A.Description
      ,A.[IsActive]
	  ,A.EffectiveDate
	  ,A.ExpirationDate
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].Diagnosis A
   left JOIN
	DBO.[DIAGNOSIS_DIM] B
	On a.Name = B.[DIAGNOSIS_NAME] and a.id = b.[DIAGNOSIS_GUID]
where B.[DIAGNOSIS_NAME] IS NULL and b.[DIAGNOSIS_GUID] is null


--Select top 1 * from DBO.[DIAGNOSIS_DIM]

----------------------------
drop table [DBO].[DOCUMENT_MODULE_TYPE_DIM]


CREATE TABLE [DBO].[DOCUMENT_MODULE_TYPE_DIM](
	[DOCUMENT_MODULE_TYPE_DIM_KEY] [INT]  IDENTITY(10000,1),
	[DOCUMENT_MODULE_CODE] AS   [DOCUMENT_MODULE_TYPE_DIM_KEY] - 9990, 
	[DOCUMENT_MODULE_GUID] [uniqueidentifier] NOT NULL,    
	[DOCUMENT_MODULE_TYPE_NAME] [VARCHAR](100) NULL,
	[DOCUMENT_MODULE_TYPE_DESC] [VARCHAR](MAX) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[CREATEDDATE] [date] NOT NULL,
	[MODIFIEDDATE] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[DOCUMENT_MODULE_TYPE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


Insert into DBO.[DOCUMENT_MODULE_TYPE_DIM]
( [DOCUMENT_MODULE_GUID],[DOCUMENT_MODULE_TYPE_NAME], [DOCUMENT_MODULE_TYPE_DESC], [ISACTIVE], [CREATEDDATE], [MODIFIEDDATE])
SELECT A.ID,A.[Name]
	  ,A.Description
      ,A.[IsActive]
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].DocumentModuleType A
   left JOIN
	DBO.[DOCUMENT_MODULE_TYPE_DIM] B
	On a.Name = B.[DOCUMENT_MODULE_TYPE_Name] and A.ID = B.[DOCUMENT_MODULE_GUID]
where B.[DOCUMENT_MODULE_TYPE_Name] IS NULL and B.[DOCUMENT_MODULE_GUID] IS NULL


--Select top 1 * from DBO.[DOCUMENT_MODULE_TYPE_DIM]

----------------------------------
drop table [DBO].[HANGFIREJOB_TYPE_DIM]

CREATE TABLE [DBO].[HANGFIREJOB_TYPE_DIM](
	[DOCUMENT_MODULE_TYPE_DIM_KEY] [INT]  IDENTITY(10000,1),
	[HANGFIREJOB_TYPE_CODE] AS   [DOCUMENT_MODULE_TYPE_DIM_KEY] - 9990, 
	[HANGFIREJOB_TYPE_GUID] [uniqueidentifier] NOT NULL,  	
	[HANGFIREJOB_TYPE_NAME] [VARCHAR](100) NULL,
	[HANGFIREJOB_TYPE_DESC] [VARCHAR](MAX) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[CREATEDDATE] [DATE] NOT NULL,
	[MODIFIEDDATE] [DATE] NULL
PRIMARY KEY CLUSTERED 
(
	[DOCUMENT_MODULE_TYPE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



Insert into DBO.[HANGFIREJOB_TYPE_DIM]
( [HANGFIREJOB_TYPE_GUID],[HANGFIREJOB_TYPE_NAME], [HANGFIREJOB_TYPE_DESC], [ISACTIVE], [CREATEDDATE], [MODIFIEDDATE])
SELECT A.ID,A.[Name]
	  ,A.Description
      ,A.[IsActive]
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].HangfireJobType A
   left JOIN
	DBO.[HANGFIREJOB_TYPE_DIM] B
	On a.Name = B.[HANGFIREJOB_TYPE_Name] and A.ID = B.[HANGFIREJOB_TYPE_GUID]
where B.[HANGFIREJOB_TYPE_Name] IS NULL AND B.[HANGFIREJOB_TYPE_GUID] IS NULL


--Select top 1 * from DBO.[HANGFIREJOB_TYPE_DIM]


-----------------------------------------

DROP TABLE [DBO].[IDENTITY_TYPE_DIM]

CREATE TABLE [DBO].[IDENTITY_TYPE_DIM](
	[IDENTITY_TYPE_DIM_KEY] [INT]  IDENTITY(10000,1), 
	[IDENTITY_TYPE_CODE] AS   [IDENTITY_TYPE_DIM_KEY] - 9990,
	[IDENTITY_TYPE_GUID] [uniqueidentifier] NOT NULL,   
	[IDENTITY_TYPE_NAME] [VARCHAR](100) NULL,
	[IDENTITY_TYPE_DESC] [VARCHAR](MAX) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[CREATEDDATE] [DATE] NOT NULL,
	[MODIFIEDDATE] [DATE] NULL
PRIMARY KEY CLUSTERED 
(
	[IDENTITY_TYPE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



Insert into DBO.[Identity_Type_DIM]
( [IDENTITY_TYPE_GUID],[Identity_Type_NAME], [Identity_Type_DESC], [ISACTIVE], [CREATEDDATE], [MODIFIEDDATE])
SELECT A.ID,A.[Name]
	  ,A.Description
      ,A.[IsActive]
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].IdentityType A
   left JOIN
	DBO.[Identity_Type_DIM] B
	On a.Name = B.[Identity_Type_Name] and A.ID= B.[IDENTITY_TYPE_GUID]
where B.[Identity_Type_Name] IS NULL AND B.[IDENTITY_TYPE_GUID] IS NULL


--Select top 1 * from DBO.[Identity_Type_DIM]


-----------------------------------------

DROP TABLE [DBO].[LANGUAGE_TYPE_DIM]

CREATE TABLE [DBO].[LANGUAGE_TYPE_DIM](
	[LANGUAGE_TYPE_DIM_KEY] [INT]  IDENTITY(10000,1), 
	[LANGUAGE_TYPE_CODE] AS   [LANGUAGE_TYPE_DIM_KEY] - 9990,
	[LANGUAGE_TYPE_GUID] [uniqueidentifier] NOT NULL,    
	[LANGUAGE_TYPE_NAME] [VARCHAR](100) NULL,
	[LANGUAGE_TYPE_DESC] [VARCHAR](MAX) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[CREATEDDATE] [DATE] NOT NULL,
	[MODIFIEDDATE] [DATE] NULL
PRIMARY KEY CLUSTERED 
(
	[LANGUAGE_TYPE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



Insert into DBO.[Language_Type_DIM]
( [LANGUAGE_TYPE_GUID],[Language_Type_NAME], [Language_Type_DESC], [ISACTIVE], [CREATEDDATE], [MODIFIEDDATE])
SELECT A.ID,A.[Name]
	  ,A.Description
      ,A.[IsActive]
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].LanguageType A
   left JOIN
	DBO.[Language_Type_DIM] B
	On a.Name = B.[Language_Type_Name] and A.ID = B.[LANGUAGE_TYPE_GUID]
where B.[Language_Type_Name] IS NULL and B.[LANGUAGE_TYPE_GUID] IS NULL 


--Select top 1 * from DBO.[Language_Type_DIM]



-----------------------------------------

DROP TABLE [DBO].[LOOKUP_TYPE_DIM]

CREATE TABLE [DBO].[LOOKUP_TYPE_DIM](
	[LOOKUP_TYPE_DIM_KEY] [INT]  IDENTITY(10000,1),
	[LOOKUP_TYPE_CODE] AS   [LOOKUP_TYPE_DIM_KEY] - 9990, 
	[LOOKUP_TYPE_GUID] [uniqueidentifier] NOT NULL,   
	[LOOKUP_TYPE_NAME] [VARCHAR](100) NULL,
	[LOOKUP_TYPE_DESC] [VARCHAR](MAX) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[CREATEDDATE] [DATE] NOT NULL,
	[MODIFIEDDATE] [DATE] NULL
PRIMARY KEY CLUSTERED 
(
	[LOOKUP_TYPE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



Insert into DBO.[Lookup_Type_DIM]
( [LOOKUP_TYPE_GUID],[Lookup_Type_NAME], [Lookup_Type_DESC], [ISACTIVE], [CREATEDDATE], [MODIFIEDDATE])
SELECT A.ID,A.[Name]
	  ,A.Description
      ,A.[IsActive]
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].LookupType A
   left JOIN
	DBO.[Lookup_Type_DIM] B
	On a.Name = B.[Lookup_Type_Name] and A.ID = B.[LOOKUP_TYPE_GUID]
where B.[Lookup_Type_Name] IS NULL and B.[LOOKUP_TYPE_GUID] IS NULL


--Select top 1 * from DBO.[Lookup_Type_DIM]
------------------------------------------------


DROP TABLE [DBO].[MODIFIER_DIM]
CREATE TABLE [DBO].[MODIFIER_DIM](
	[MODIFIER_DIM_KEY] [INT]  IDENTITY(10000,1), 
	[MODIFIER_CODE] AS   [MODIFIER_DIM_KEY] - 9990,
	[MODIFIER_GUID] [uniqueidentifier] NOT NULL,     
	[MODIFIER_NAME] [VARCHAR](50) NOT NULL,
	[MODIFIER_SHORT_DESC] [VARCHAR](MAX) NULL,
	[MODIFIER_LONG_DESC] [VARCHAR](MAX) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[EFFECTIVEDATE] [DATE] NULL,
	[EXPIRATIONDATE] [DATE] NULL,
	[CREATEDDATE] [DATE] NULL,
	[MODIFIEDDATE] [DATE] NULL,
PRIMARY KEY CLUSTERED 
(
	[MODIFIER_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


Insert into DBO.[Modifier_DIM]
( [MODIFIER_GUID],[Modifier_NAME], [MODIFIER_SHORT_DESC],[MODIFIER_LONG_DESC], [ISACTIVE], [EFFECTIVEDATE], [EXPIRATIONDATE], [CREATEDDATE], [MODIFIEDDATE])
SELECT A.ID,A.[Name]
	  ,A.ShortDescription
	  ,A.LongDescription
      ,A.[IsActive]
	  ,A.EffectiveDate
	  ,A.ExpirationDate
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].Modifier A
   left JOIN
	DBO.[Modifier_DIM] B
	On a.Name = B.[Modifier_NAME] and A.ID = B.[MODIFIER_GUID]
where B.[Modifier_NAME] IS NULL and B.[MODIFIER_GUID] IS NULL


--Select top 1 * from DBO.[Modifier_DIM]

----------------------------------------------------
DROP TABLE [DBO].[NOTE_TYPE_DIM]

CREATE TABLE [DBO].[NOTE_TYPE_DIM](
	[NOTE_TYPE_DIM_KEY] [INT]  IDENTITY(10000,1), 
	[NOTE_TYPE_CODE] AS   [NOTE_TYPE_DIM_KEY] - 9990, 
	[NOTE_TYPE_GUID] [uniqueidentifier] NOT NULL,   
	[NOTE_TYPE_NAME] [VARCHAR](100) NULL,
	[NOTE_TYPE_DESC] [VARCHAR](MAX) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[CREATEDDATE] [DATE] NOT NULL,
	[MODIFIEDDATE] [DATE] NULL
PRIMARY KEY CLUSTERED 
(
	[NOTE_TYPE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



Insert into DBO.[Note_Type_DIM]
( [NOTE_TYPE_GUID],[Note_Type_NAME], [Note_Type_DESC], [ISACTIVE], [CREATEDDATE], [MODIFIEDDATE])
SELECT A.ID,A.[Name]
	  ,A.Description
      ,A.[IsActive]
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].NoteType A
   left JOIN
	DBO.[Note_Type_DIM] B
	On a.Name = B.[Note_Type_Name] and A.ID = B.[NOTE_TYPE_GUID]
where B.[Note_Type_Name] IS NULL AND B.[NOTE_TYPE_GUID] IS NULL


--Select top 1 * from DBO.[Note_Type_DIM]



----------------------------------------------------
DROP TABLE [DBO].[PERSONALINFORMATION_TYPE_DIM]

CREATE TABLE [DBO].[PERSONALINFORMATION_TYPE_DIM](
	[PERSONALINFORMATION_TYPE_DIM_KEY] [INT]  IDENTITY(10000,1), 
	[PERSONALINFORMATION_TYPE_CODE] AS   [PERSONALINFORMATION_TYPE_DIM_KEY] - 9990,
	[PERSONALINFORMATION_TYPE_GUID] [uniqueidentifier] NOT NULL,   
	[PERSONALINFORMATION_TYPE_NAME] [VARCHAR](100) NULL,
	[PERSONALINFORMATION_TYPE_DESC] [VARCHAR](MAX) NULL,
	[ISDELETED] [BIT] NOT NULL,
	[CREATEDDATE] [DATE] NOT NULL,
	[MODIFIEDDATE] [DATE] NULL
PRIMARY KEY CLUSTERED 
(
	[PERSONALINFORMATION_TYPE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



Insert into DBO.[PersonalInformation_Type_DIM]
( [PERSONALINFORMATION_TYPE_GUID],[PersonalInformation_Type_NAME], [PersonalInformation_Type_DESC], [ISDELETED], [CREATEDDATE], [MODIFIEDDATE])
SELECT A.ID,A.[Name]
	  ,A.Description
      ,A.IsDeleted
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].PersonalInformationType A
   left JOIN
	DBO.[PersonalInformation_Type_DIM] B
	On a.Name = B.[PersonalInformation_Type_Name] and A.ID = B.[PERSONALINFORMATION_TYPE_GUID]
where B.[PersonalInformation_Type_Name] IS NULL and B.[PERSONALINFORMATION_TYPE_GUID] IS NULL


--Select top 1 * from DBO.[PersonalInformation_Type_DIM]



----------------------------------------------------
DROP TABLE [DBO].[Phone_Type_DIM]

CREATE TABLE [DBO].[PHONE_TYPE_DIM](
	[PHONE_TYPE_DIM_KEY] [INT]  IDENTITY(10000,1), 
	[PHONE_TYPE_CODE] AS   [PHONE_TYPE_DIM_KEY] - 9990,
	[PHONE_TYPE_GUID] [uniqueidentifier] NOT NULL,    
	[PHONE_TYPE_NAME] [VARCHAR](100) NULL,
	[PHONE_TYPE_DESC] [VARCHAR](MAX) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[CREATEDDATE] [DATE] NOT NULL,
	[MODIFIEDDATE] [DATE] NULL
PRIMARY KEY CLUSTERED 
(
	[PHONE_TYPE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



Insert into DBO.[Phone_Type_DIM]
( [PHONE_TYPE_GUID],[Phone_Type_NAME], [Phone_Type_DESC], [ISACTIVE], [CREATEDDATE], [MODIFIEDDATE])
SELECT A.ID,A.[Name]
	  ,A.Description
      ,A.[IsActive]
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].PhoneType A
   left JOIN
	DBO.[Phone_Type_DIM] B
	On a.Name = B.[Phone_Type_Name] and a.id = B.[PHONE_TYPE_GUID]
where B.[Phone_Type_Name] IS NULL and B.[PHONE_TYPE_GUID] IS NULL


--Select top 1 * from DBO.[Phone_Type_DIM]


----------------------------------------------------
DROP TABLE [DBO].[PLACEOFSERVICE_DIM]

CREATE TABLE [DBO].[PLACEOFSERVICE_DIM](
	[PLACEOFSERVICE_DIM_KEY] [INT]  IDENTITY(10000,1),
	[PLACEOFSERVICE_CODE] AS   [PLACEOFSERVICE_DIM_KEY] - 9990,
	[PLACEOFSERVICE_GUID] [uniqueidentifier] NOT NULL,      
	[PLACEOFSERVICE_NAME] [VARCHAR](100) NULL,
	[PLACEOFSERVICE_DESC] [VARCHAR](MAX) NULL
PRIMARY KEY CLUSTERED 
(
	[PLACEOFSERVICE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



Insert into DBO.[PLACEOFSERVICE_DIM]
( [PLACEOFSERVICE_GUID],[PLACEOFSERVICE_NAME], [PLACEOFSERVICE_DESC])
SELECT A.ID,A.[Name]
	  ,A.Description      
  FROM [THM].[ref].PlaceOfService A
   left JOIN
	DBO.[PLACEOFSERVICE_DIM] B
	On a.Name = B.[PLACEOFSERVICE_NAME] and A.ID = B.[PLACEOFSERVICE_GUID]
where B.[PLACEOFSERVICE_NAME] IS NULL and B.[PLACEOFSERVICE_GUID] IS NULL


--Select top 1 * from DBO.[PLACEOFSERVICE_DIM]

----------------------------------------------------
DROP TABLE [DBO].[Preference_DIM]

CREATE TABLE [DBO].[PREFERENCE_DIM](
	[PREFERENCE_DIM_KEY] [INT]  IDENTITY(10000,1), 
	[PREFERENCE_CODE] AS   [PREFERENCE_DIM_KEY] - 9990, 
	[PREFERENCE_GUID] [uniqueidentifier] NOT NULL,     
	[PREFERENCE_NAME] [VARCHAR](100) NULL,
	[PREFERENCE_DESC] [VARCHAR](MAX) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[CREATEDDATE] [DATE] NOT NULL,
	[MODIFIEDDATE] [DATE] NULL
PRIMARY KEY CLUSTERED 
(
	[PREFERENCE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



Insert into DBO.[Preference_DIM]
( [PREFERENCE_GUID],[Preference_NAME], [Preference_DESC], [ISACTIVE], [CREATEDDATE], [MODIFIEDDATE])
SELECT A.ID,A.[Name]
	  ,A.Description
      ,A.[IsActive]
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].Preference A
   left JOIN
	DBO.[Preference_DIM] B
	On a.Name = B.[Preference_Name] and A.id = B.[PREFERENCE_GUID]
where B.[Preference_Name] IS NULL and B.[PREFERENCE_GUID] IS NULL


--Select top 1 * from DBO.[Preference_DIM]


----------------------------------------------------
DROP TABLE [DBO].[Qual_DIM]

CREATE TABLE [DBO].[QUAL_DIM](
	[QUAL_DIM_KEY] [INT]  IDENTITY(10000,1), 
	[QUAL_CODE] AS   [QUAL_DIM_KEY] - 9990,
	[QUAL_GUID] [uniqueidentifier] NOT NULL,       
	[QUAL_NAME] [VARCHAR](100) NULL,
	[QUAL_DESC] [VARCHAR](MAX) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[CREATEDDATE] [DATE] NOT NULL,
	[MODIFIEDDATE] [DATE] NULL
PRIMARY KEY CLUSTERED 
(
	[QUAL_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



Insert into DBO.[Qual_DIM]
( [QUAL_GUID],[Qual_NAME], [Qual_DESC], [ISACTIVE], [CREATEDDATE], [MODIFIEDDATE])
SELECT A.ID,A.[Name]
	  ,A.Description
      ,A.[IsActive]
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].Qual A
   left JOIN
	DBO.[Qual_DIM] B
	On a.Name = B.[Qual_Name] and A.ID = B.[QUAL_GUID]
where B.[Qual_Name] IS NULL AND B.[QUAL_GUID] IS NULL


--Select top 1 * from DBO.[Qual_DIM]

----------------------------------------------------
DROP TABLE [DBO].[ReferralStatus_Type_DIM]

CREATE TABLE [DBO].[REFERRALSTATUS_TYPE_DIM](
	[REFERRALSTATUS_TYPE_DIM_KEY] [INT]  IDENTITY(10000,1),
	[REFERRALSTATUS_TYPE_CODE] AS   [REFERRALSTATUS_TYPE_DIM_KEY] - 9990,  
	[REFERRALSTATUS_TYPE_GUID] [uniqueidentifier] NOT NULL,     
	[REFERRALSTATUS_TYPE_NAME] [VARCHAR](100) NULL,
	[REFERRALSTATUS_TYPE_DESC] [VARCHAR](MAX) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[CREATEDDATE] [DATE] NOT NULL,
	[MODIFIEDDATE] [DATE] NULL
PRIMARY KEY CLUSTERED 
(
	[REFERRALSTATUS_TYPE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



Insert into DBO.[ReferralStatus_Type_DIM]
( [REFERRALSTATUS_TYPE_GUID],[ReferralStatus_Type_NAME], [ReferralStatus_Type_DESC], [ISACTIVE], [CREATEDDATE], [MODIFIEDDATE])
SELECT A.ID,A.[Name]
	  ,A.Description
      ,A.[IsActive]
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].ReferralStatusType A
   left JOIN
	DBO.[ReferralStatus_Type_DIM] B
	On a.Name = B.[ReferralStatus_Type_Name] and A.ID = B.[REFERRALSTATUS_TYPE_GUID]
where B.[ReferralStatus_Type_Name] IS NULL AND B.[REFERRALSTATUS_TYPE_GUID] IS NULL


--Select top 1 * from DBO.[ReferralStatus_Type_DIM]

----------------------------------------------------
DROP TABLE [DBO].[Referral_SUBStatus_Type_DIM]

CREATE TABLE [DBO].[REFERRAL_SUBSTATUS_TYPE_DIM](
	[REFERRAL_SUBSTATUS_TYPE_DIM_KEY] [INT]  IDENTITY(10000,1),
	[REFERRAL_SUBSTATUS_TYPE_CODE] AS   [REFERRAL_SUBSTATUS_TYPE_DIM_KEY] - 9990, 
	[REFERRAL_SUBSTATUS_TYPE_GUID] [uniqueidentifier] NOT NULL,     
	[REFERRAL_SUBSTATUS_TYPE_NAME] [VARCHAR](100) NULL,
	[REFERRAL_SUBSTATUS_TYPE_DESC] [VARCHAR](MAX) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[CREATEDDATE] [DATE] NOT NULL,
	[MODIFIEDDATE] [DATE] NULL
PRIMARY KEY CLUSTERED 
(
	[REFERRAL_SUBSTATUS_TYPE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



Insert into DBO.[REFERRAL_SUBSTATUS_TYPE_DIM]
( [REFERRAL_SUBSTATUS_TYPE_GUID],[REFERRAL_SUBSTATUS_TYPE_NAME], [REFERRAL_SUBSTATUS_TYPE_DESC], [ISACTIVE], [CREATEDDATE], [MODIFIEDDATE])
SELECT rss.ID,A.[Name]
	  ,rss.[SubStatusName]
      ,A.[IsActive]
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].ReferralStatusType A
  join [THM].[ref].[ReferralSubStatusType] rss on rss.ReferralStatusTypeId = A.id
    left JOIN
	DBO.[REFERRAL_SUBSTATUS_TYPE_DIM] B
	On a.Name = B.[REFERRAL_SUBSTATUS_TYPE_NAME] and rss.[SubStatusName] = B.[REFERRAL_SUBSTATUS_TYPE_DESC] and 
	A.ID = B.[REFERRAL_SUBSTATUS_TYPE_GUID]
where B.[REFERRAL_SUBSTATUS_TYPE_NAME] IS NULL and B.[REFERRAL_SUBSTATUS_TYPE_DESC] is NULL and B.[REFERRAL_SUBSTATUS_TYPE_GUID] IS NULL


--Select top 1 * from DBO.[REFERRAL_SUBSTATUS_TYPE_DIM]


------------------------------------------------------
--DROP TABLE [DBO].[Service_Source_DIM]

--CREATE TABLE [DBO].[SERVICE_SOURCE_DIM](
--	[SERVICE_SOURCE_DIM_KEY] [INT]  IDENTITY(10000,1),
--	[SERVICE_SOURCE_CODE] AS   [SERVICE_SOURCE_DIM_KEY] - 9990,    
--	[SERVICE_SOURCE_NAME] [VARCHAR](100) NULL,
--	[SERVICE_SOURCE_DESC] [VARCHAR](MAX) NULL,
--	[CREATEDDATE] [DATE] NOT NULL,
--	[MODIFIEDDATE] [DATE] NULL
--PRIMARY KEY CLUSTERED 
--(
--	[SERVICE_SOURCE_DIM_KEY] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
--) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
--GO



--Insert into DBO.[Service_Source_DIM]
--( [Service_Source_NAME], [Service_Source_DESC],  [CREATEDDATE], [MODIFIEDDATE])
--SELECT A.ServiceSourceName
--	  ,A.Description
--      ,A.[CreatedDate]
--      ,A.[ModifiedDate]
--  FROM [THM].[ref].ServiceSource A
--   left JOIN
--	DBO.[Service_Source_DIM] B
--	On a.ServiceSourceName = B.[Service_Source_Name]
--where B.[Service_Source_Name] IS NULL


----Select top 1 * from DBO.[Service_Source_DIM]





----------------------------------------------------
DROP TABLE [DBO].[Source_Type_DIM]

CREATE TABLE [DBO].[SOURCE_TYPE_DIM](
	[SOURCE_TYPE_DIM_KEY] [INT]  IDENTITY(10000,1),
	[SOURCE_TYPE_CODE] AS   [SOURCE_TYPE_DIM_KEY] - 9990,
	[SOURCE_TYPE_GUID] [uniqueidentifier] NOT NULL,      
	[SOURCE_TYPE_NAME] [VARCHAR](100) NULL,
	[SOURCE_TYPE_DESC] [VARCHAR](MAX) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[CREATEDDATE] [DATE] NOT NULL,
	[MODIFIEDDATE] [DATE] NULL
PRIMARY KEY CLUSTERED 
(
	[SOURCE_TYPE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



Insert into DBO.[Source_Type_DIM]
( [SOURCE_TYPE_GUID],[Source_Type_NAME], [Source_Type_DESC], [ISACTIVE], [CREATEDDATE], [MODIFIEDDATE])
SELECT A.ID,A.[Name]
	  ,A.Description
      ,A.[IsActive]
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].SourceType A
   left JOIN
	DBO.[Source_Type_DIM] B
	On a.Name = B.[Source_Type_Name] and A.ID = B.[SOURCE_TYPE_GUID]
where B.[Source_Type_Name] IS NULL and B.[SOURCE_TYPE_GUID] IS NULL


--Select top 1 * from DBO.[Source_Type_DIM]

----------------------------------------------------
DROP TABLE [DBO].[Treatment_Type_DIM]

CREATE TABLE [DBO].[TREATMENT_TYPE_DIM](
	[TREATMENT_TYPE_DIM_KEY] [INT]  IDENTITY(10000,1),
	[TREATMENT_TYPE_CODE] AS   [TREATMENT_TYPE_DIM_KEY] - 9990, 
	[TREATMENT_TYPE_GUID] [uniqueidentifier] NOT NULL,      
	[TREATMENT_TYPE_NAME] [VARCHAR](100) NULL,
	[TREATMENT_TYPE_DESC] [VARCHAR](MAX) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[CREATEDDATE] [DATE] NOT NULL,
	[MODIFIEDDATE] [DATE] NULL
PRIMARY KEY CLUSTERED 
(
	[TREATMENT_TYPE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



Insert into DBO.[Treatment_Type_DIM]
([TREATMENT_TYPE_GUID], [Treatment_Type_NAME], [Treatment_Type_DESC], [ISACTIVE], [CREATEDDATE], [MODIFIEDDATE])
SELECT A.ID,A.[Name]
	  ,A.Description
      ,A.[IsActive]
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[ref].TreatmentType A
   left JOIN
	DBO.[Treatment_Type_DIM] B
	On a.Name = B.[Treatment_Type_Name] and A.ID = B.[TREATMENT_TYPE_GUID]
where B.[Treatment_Type_Name] IS NULL and B.[TREATMENT_TYPE_GUID] IS NULL


--Select top 1 * from DBO.[Treatment_Type_DIM]

------------------------------------------------------------------------


DROP TABLE [DBO].[TREATMENT_SERVICE_PRODUCT_DIM]

CREATE TABLE [DBO].TREATMENT_SERVICE_PRODUCT_DIM(
	[TREATMENT_SERVICE_PRODUCT_DIM_KEY] [INT]  IDENTITY(10000,1),
	[TREATMENT_SERVICE_PRODUCT_CODE] AS   [TREATMENT_SERVICE_PRODUCT_DIM_KEY] - 9990, 
	[TREATMENT_SERVICE_PRODUCT_GUID] [uniqueidentifier] NOT NULL,       
	[TREATMENT_TYPE_NAME] [VARCHAR](100) NULL,   
	[TREATMENT_TYPE_SERVICE_NAME] [VARCHAR](100) NULL,
	[TREATMENT_TYPE_PRODUCT_DESC] [VARCHAR](MAX) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[CREATEDDATE] [DATE] NOT NULL,
	[MODIFIEDDATE] [DATE] NULL
PRIMARY KEY CLUSTERED 
(
	[TREATMENT_SERVICE_PRODUCT_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



Insert into DBO.TREATMENT_SERVICE_PRODUCT_DIM
( [TREATMENT_SERVICE_PRODUCT_GUID],[TREATMENT_TYPE_NAME], [TREATMENT_TYPE_SERVICE_NAME], [TREATMENT_TYPE_PRODUCT_DESC],[ISACTIVE], [CREATEDDATE], [MODIFIEDDATE])
SELECT PT.ID,tt.[Name] treatment_type
	  ,st.name as service_type
	  ,pt.name as product_type
      ,tt.[IsActive]
      ,tt.[CreatedDate]
      ,tt.[ModifiedDate]
  FROM [THM].[ref].TreatmentType tt
  join [THM].[ref].[ServiceType] st on st.treatmenttypeid = tt.id
join [THM].[ref].[ServiceProductMap] spm on spm.servicetypeid = st.id
join [THM].[ref].[ProductType] pt on pt.id = spm.producttypeid
   left JOIN
	DBO.TREATMENT_SERVICE_PRODUCT_DIM B
	On tt.Name = B.[TREATMENT_TYPE_NAME] and st.name = b.[TREATMENT_TYPE_SERVICE_NAME] and pt.name = B.[TREATMENT_TYPE_PRODUCT_DESC]
	and PT.ID = B.[TREATMENT_SERVICE_PRODUCT_GUID]
where B.[TREATMENT_TYPE_NAME] IS NULL and B.[TREATMENT_TYPE_SERVICE_NAME] is null and  B.[TREATMENT_TYPE_PRODUCT_DESC] is null
and B.[TREATMENT_SERVICE_PRODUCT_GUID] IS NULL
order by treatment_type, service_type

--Select top 1 * from DBO.TREATMENT_SERVICE_PRODUCT_DIM

------------------------------------------------------------------------

----------------------------------------------------
DROP TABLE [DBO].[BID_REJECTION_REASON_DIM]

CREATE TABLE [DBO].[BID_REJECTION_REASON_DIM](
	[BID_REJECTION_REASON_DIM_KEY] [INT]  IDENTITY(10000,1),
	[BID_REJECTION_REASON_CODE] AS   [BID_REJECTION_REASON_DIM_KEY] - 9990, 
	[BID_REJECTION_REASON_GUID] [uniqueidentifier] NOT NULL,        
	[BID_REJECTION_REASON_NAME] [VARCHAR](100) NULL,
	[BID_REJECTION_REASON_DESC] [VARCHAR](MAX) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[CREATEDDATE] [DATE] NOT NULL,
	[MODIFIEDDATE] [DATE] NULL
PRIMARY KEY CLUSTERED 
(
	[BID_REJECTION_REASON_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

Insert into DBO.[BID_REJECTION_REASON_DIM]
( [BID_REJECTION_REASON_GUID],[BID_REJECTION_REASON_NAME], [BID_REJECTION_REASON_DESC], [ISACTIVE], [CREATEDDATE], [MODIFIEDDATE])
SELECT A.ID,A.[Name] bid_rejection_reason
	  ,A.Description
      ,A.IsDeleted
      ,A.[CreatedDate]
      ,A.[ModifiedDate]
  FROM [THM].[dbo].[Lookup] A
   left JOIN
	DBO.[BID_REJECTION_REASON_DIM] B
	On a.Name = B.[BID_REJECTION_REASON_NAME] and A.ID = B.[BID_REJECTION_REASON_GUID]
 where a.lookuptypeid='EA591A7B-EFB1-4DA9-980B-9C6FC224C892'
 and B.[BID_REJECTION_REASON_NAME] IS NULL and B.[BID_REJECTION_REASON_GUID] IS NULL



--Select top 1 * from DBO.[BID_REJECTION_REASON_DIM]

-------------------------------------------------------
drop table [DBO].[CLIENT_DIM]
CREATE TABLE [DBO].[CLIENT_DIM](
	[CLIENT_DIM_KEY] [INT]  IDENTITY(10000,1), 
	[CLIENT_DIM_CODE] AS   [CLIENT_DIM_KEY] - 9990, 
	[PARENT_CLIENT_GUID] [UNIQUEIDENTIFIER] NOT NULL,      
	[SUB_CLIENT_GUID] [UNIQUEIDENTIFIER] NOT NULL,      
	[PARENT_CLIENT_NAME] [VARCHAR](50) NOT NULL,
	[SUB_CLIENT_NAME] [VARCHAR](MAX) NULL,
	[CLIENT_TYPE] [VARCHAR](MAX) NULL,
	[EFFECTIVEDATE] [date] NULL,
	[EXPIRATIONDATE] [date] NULL,
	[CLIENT_EXTERNAL_ID] [VARCHAR](50)  NULL,
	[CLIENT_CODE] [INT] NOT NULL,
	[ISDELETED] [BIT] NOT NULL,
	[CREATEDDATE] [date] NULL,
	[MODIFIEDDATE] [date] NULL	
PRIMARY KEY CLUSTERED 
(
	[CLIENT_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


Insert into DBO.[CLIENT_DIM]
( [PARENT_CLIENT_GUID],[SUB_CLIENT_GUID],[PARENT_CLIENT_NAME], [SUB_CLIENT_NAME], [CLIENT_TYPE], [EFFECTIVEDATE], [EXPIRATIONDATE], [CLIENT_EXTERNAL_ID], [CLIENT_CODE], [ISDELETED], [CREATEDDATE], [MODIFIEDDATE])
SELECT CC.ID,C.ID,cc.[ClientName] as PARENT_CLIENT_NAME
	  ,c.[ClientName] as subclient_NAME
	  ,ct.[name] as client_type 
	  ,C.EffectiveDate
	  ,C.ExpirationDate
	  ,C.[ExternalId]
	  ,C.[ClientCode]
      ,C.[ISDELETED]
	  ,C.[CreatedDate]
      ,C.[ModifiedDate]
  FROM [THM].[payor].[Client] c
  join [THM].[payor].[Client] cc on cc.id = c.parentid
  join [THM].[ref].[ClientType] ct on ct.id = c.clienttypeid
   left JOIN
	DBO.[CLIENT_DIM] B
	On CC.[ClientName] = B.[PARENT_CLIENT_NAME] and C.[ClientName] = B.[SUB_CLIENT_NAME]
	and CT.[Name] = B.[CLIENT_TYPE] and CC.ID = B.[PARENT_CLIENT_GUID] and c.id = B.[SUB_CLIENT_GUID]
where B.[PARENT_CLIENT_NAME]IS NULL and B.[SUB_CLIENT_NAME] is null and B.[CLIENT_TYPE]  is NULL AND B.[PARENT_CLIENT_GUID] IS NULL
and B.[SUB_CLIENT_GUID] is null
 order by CC.ID

--Select top 1 * from DBO.[CLIENT_DIM]



  -------------------------------------------------------
drop table [DBO].[IW_DIM]
CREATE TABLE [DBO].[IW_DIM](
	[IW_DIM_KEY] [INT]  IDENTITY(10000,1), 
	[IW_DIM_CODE] AS   [IW_DIM_KEY] - 9990,
	[IW_GUID] [uniqueidentifier] NOT NULL,  
	[IW_FIRST_NAME] [VARCHAR](100)  NULL,
	[IW_MIDDLE_NAME] [VARCHAR](100)  NULL,
	[IW_LAST_NAME] [VARCHAR](100)  NULL,
	[IW_PHONE_NUMBER] [VARCHAR](10) NULL,
	[IW_PHONE_TYPE] [VARCHAR](100)  NULL,
	[IW_PHONE_CONTACT_TYPE] [VARCHAR](100)  NULL,
	[IW_EMAIL] [VARCHAR](100) NULL,
	[IW_IDENTITY_NUMBER] [VARCHAR](100) NULL,
	[CREATEDDATE] [date] NULL,
	[MODIFIEDDATE] [date] NULL	
PRIMARY KEY CLUSTERED 
(
	[IW_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] 
GO


Insert into DBO.[IW_DIM]
([IW_GUID],[IW_FIRST_NAME], [IW_MIDDLE_NAME], [IW_LAST_NAME], [IW_PHONE_NUMBER], [IW_PHONE_TYPE], [IW_PHONE_CONTACT_TYPE], [IW_EMAIL], [IW_IDENTITY_NUMBER], [CREATEDDATE], [MODIFIEDDATE])
SELECT
	   A.ID,A.[FirstName] as	IW_FIRST_NAME
      ,A.[MiddleName] AS IW_MIDDLENAME
      ,A.[LastName] AS IW_LASTNAME
	  ,PH.PHONENUMBER
	  ,PT.NAME AS PHONE_TYPE
	  ,CT.NAME AS PHONE_CONTACT_TYPE
	  ,C.EMAIL
	  ,i.[IdentityNumber]
	  ,A.CreatedDate
	  ,A.ModifiedDate    
  FROM [THM].[dbo].[Actor] A
  JOIN [THM].[dbo].[ActorPhoneMap] AP ON AP.ACTORID = A.ID
  JOIN [THM].[dbo].[Phone] PH ON PH.ID = AP.PHONEID
  JOIN [THM].[ref].[PhoneType] PT ON PT.ID = PH.PHONETYPEID
  JOIN [THM].[dbo].[ActorContactMap] ACM ON ACM.ACTORID = A.ID
  JOIN [THM].[dbo].[Contact] C ON C.ID = ACM.CONTACTID 
  JOIN [THM].[ref].[ContactType] CT ON CT.ID = C.CONTACTTYPEID
left outer join [THM].[dbo].[ActorIdentityMap] aim on aim.actorid = a.id
left outer join [THM].[dbo].[Identity] i on i.id = aim.identityid
  left JOIN
	DBO.[IW_DIM] B
	On  A.[FirstName]= B.[IW_FIRST_NAME] and A.[MiddleName] = B.[IW_MIDDLE_NAME] and A.[LastName] = B.[IW_LAST_NAME]
		AND PH.PHONENUMBER = B.[IW_PHONE_NUMBER] and PT.NAME = B.[IW_PHONE_TYPE] and CT.NAME = B.[IW_PHONE_CONTACT_TYPE]
		AND C.EMAIL = B.[IW_EMAIL] and i.[IdentityNumber] = B.[IW_IDENTITY_NUMBER]
		and A.ID = B.[IW_GUID]
 WHERE	A.actortypeid = '4830EAF0-DFEA-4069-A523-1393CE607F8C'
 AND B.[IW_FIRST_NAME] IS NULL AND  B.[IW_MIDDLE_NAME] IS NULL AND B.[IW_LAST_NAME] IS NULL AND B.[IW_PHONE_NUMBER] IS NULL AND
	 B.[IW_PHONE_TYPE]IS NULL AND B.[IW_PHONE_CONTACT_TYPE] IS NULL AND B.[IW_EMAIL] IS NULL AND B.[IW_IDENTITY_NUMBER] IS NULL 
	 AND B.[IW_GUID] IS NULL
 ORDER BY A.ID

--Select top 1 * from DBO.[IW_DIM]

------------------------------------------------------------


DROP TABLE [DBO].[SERVICE_TYPE_DIM]

CREATE TABLE [DBO].[SERVICE_TYPE_DIM](
	[SERVICE_TYPE_DIM_KEY] [INT]  IDENTITY(10000,1),
	[SERVICE_TYPE_CODE] AS   [SERVICE_TYPE_DIM_KEY] - 9990,
	[SERVICE_TYPE_GUID] [uniqueidentifier] NOT NULL,    
	[SERVICE_TYPE_NAME] [VARCHAR](100) NULL,  
	[SERVICE_TYPET_DESC] [VARCHAR](MAX) NULL, 
	[SERVICE_TYPE_TREATMENT_TYPE_NAME] [VARCHAR](100) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[CREATEDDATE] [DATE] NOT NULL,
	[MODIFIEDDATE] [DATE] NULL
PRIMARY KEY CLUSTERED 
(
	[SERVICE_TYPE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



Insert into DBO.[SERVICE_TYPE_DIM]
([SERVICE_TYPE_GUID],[SERVICE_TYPE_NAME], [SERVICE_TYPET_DESC], [SERVICE_TYPE_TREATMENT_TYPE_NAME], [ISACTIVE], [CREATEDDATE], [MODIFIEDDATE])
SELECT st.ID,st.name as service_type
	   ,st.Description
	   ,tt.[Name] treatment_type	  
	   ,st.[IsActive]
      ,st.[CreatedDate]
      ,st.[ModifiedDate]
  FROM [THM].[ref].TreatmentType tt 
  join [THM].[ref].[ServiceType] st on st.treatmenttypeid = tt.id
   left JOIN
	DBO.[SERVICE_TYPE_DIM] B
	On st.Name = B.[SERVICE_TYPE_NAME] and st.Description = b.[SERVICE_TYPET_DESC] and tt.[Name] = B.[SERVICE_TYPE_TREATMENT_TYPE_NAME]
	and st.ID = B.[SERVICE_TYPE_GUID]
where B.[SERVICE_TYPE_NAME] IS NULL and B.[SERVICE_TYPET_DESC] is null and  B.[SERVICE_TYPE_TREATMENT_TYPE_NAME] is null
AND B.[SERVICE_TYPE_GUID] IS nULL
order by st.name, tt.[Name]

--Select top 1 * from DBO.[SERVICE_TYPE_DIM]

------------------------------------------------------------------------


------------------------------------------------------------


DROP TABLE [DBO].[PRODUCT_TYPE_DIM]

CREATE TABLE [DBO].[PRODUCT_TYPE_DIM](
	[PRODUCT_TYPE_DIM_KEY] [INT]  IDENTITY(10000,1),
	[PRODUCT_TYPE_CODE] AS   [PRODUCT_TYPE_DIM_KEY] - 9990, 
	[PRODUCT_TYPE_GUID] [uniqueidentifier] NOT NULL,    
	[PRODUCT_TYPE_NAME] [VARCHAR](100) NULL,  
	[PRODUCT_TYPET_DESC] [VARCHAR](MAX) NULL, 
	[PRODUCT_TYPE_TREATMENT_TYPE_NAME] [VARCHAR](100) NULL,
	[ISACTIVE] [BIT] NOT NULL,
	[CREATEDDATE] [DATE] NOT NULL,
	[MODIFIEDDATE] [DATE] NULL
PRIMARY KEY CLUSTERED 
(
	[PRODUCT_TYPE_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



Insert into DBO.[PRODUCT_TYPE_DIM]
([PRODUCT_TYPE_GUID],[PRODUCT_TYPE_NAME], [PRODUCT_TYPET_DESC], [PRODUCT_TYPE_TREATMENT_TYPE_NAME], [ISACTIVE], [CREATEDDATE], [MODIFIEDDATE])
SELECT PT.ID,PT.name as PRODUCT_TYPE
	   ,PT.Description
	   ,tt.[Name] treatment_type	  
	   ,PT.[IsActive]
      ,PT.[CreatedDate]
      ,PT.[ModifiedDate]
  FROM THM.[ref].[ProductType] PT left join [THM].[ref].TreatmentType tt 
    on PT.treatmenttypeid = tt.id
   left JOIN
	DBO.[PRODUCT_TYPE_DIM] B
	On PT.Name = B.[PRODUCT_TYPE_NAME] and PT.Description = b.[PRODUCT_TYPET_DESC] and tt.[Name] = B.[PRODUCT_TYPE_TREATMENT_TYPE_NAME]
	and PT.ID = B.[PRODUCT_TYPE_GUID]
where B.[PRODUCT_TYPE_NAME] IS NULL and B.[PRODUCT_TYPET_DESC] is null and  B.[PRODUCT_TYPE_TREATMENT_TYPE_NAME] is null
AND B.[PRODUCT_TYPE_GUID] IS NULL
order by PT.name, tt.[Name]

--Select top 1 * from DBO.[PRODUCT_TYPE_DIM]

------------------------------------------------------------------------

DROP TABLE DBO.[ZIP_CODES_STATES_DIM]
CREATE TABLE DBO.[ZIP_CODES_STATES_DIM](
	[ZIP_CODES_STATES_DIM_KEY] [INT]  IDENTITY(10000,1), 
	[ZIP_CODES_STATES_CODE] AS   [ZIP_CODES_STATES_DIM_KEY] - 9990, 
	[ZIP_CODES_STATES_GUID] [UNIQUEIDENTIFIER] NULL,
	[ZIP_CODES_STATES_ZIPCODE] [VARCHAR](50) NULL,
	[ZIP_CODES_STATES_CITY] [VARCHAR](50) NULL,
	[ZIP_CODES_STATES_STATECODE] [VARCHAR](50) NULL,
	[ZIP_CODES_STATES_COUNTY] [VARCHAR](50) NULL,
	[ZIP_CODES_STATES_STATE] [VARCHAR](50) NULL,
	[ZIP_CODES_STATES_TYPE] [VARCHAR](50) NULL,
	[ZIP_CODES_STATES_TIMEZONE] [VARCHAR](10) NULL,
	[ZIP_CODES_STATES_DAYLIGHTSAVING] [BIT] NULL,
	[CREATEDDATE] [DATE]  NULL,
	[MODIFIEDDATE] [DATE] NULL
PRIMARY KEY CLUSTERED 
(
	[ZIP_CODES_STATES_DIM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] 
GO


Insert into DBO.[ZIP_CODES_STATES_DIM]
( [ZIP_CODES_STATES_ZIPCODE], [ZIP_CODES_STATES_CITY], [ZIP_CODES_STATES_STATECODE], [ZIP_CODES_STATES_COUNTY], [ZIP_CODES_STATES_STATE],
 [ZIP_CODES_STATES_TYPE], [ZIP_CODES_STATES_TIMEZONE], [ZIP_CODES_STATES_DAYLIGHTSAVING],[CREATEDDATE])
SELECT A.[ZipCode]
      ,A.[City]
      ,A.[StateCode]
      ,A.[County]
      ,A.[State]
      ,A.[Type]
      ,A.[TimeZone]
      ,A.[DayLightSaving]
      ,CURRENT_TIMESTAMP	  
  FROM [APA].[dbo].[ZipCodesStates] A
   left JOIN
	DBO.[ZIP_CODES_STATES_DIM] B
	On a.[ZipCode] = B.[ZIP_CODES_STATES_ZIPCODE] and a.[City] = b.[ZIP_CODES_STATES_CITY]
		and a.[StateCode] = b.[ZIP_CODES_STATES_STATECODE]
		and a.[County] = b.[ZIP_CODES_STATES_COUNTY]
		and a.[State] = b.[ZIP_CODES_STATES_STATE]
where B.[ZIP_CODES_STATES_ZIPCODE] IS NULL and b.[ZIP_CODES_STATES_CITY] is null and b.[ZIP_CODES_STATES_STATECODE] is null
	 and b.[ZIP_CODES_STATES_COUNTY] is null and b.[ZIP_CODES_STATES_STATE] is null

--Select top 100 * from DBO.[ZIP_CODES_STATES_DIM]



/****** Object:  Index [Idx_ZipCodesStates_Zipcode]    Script Date: 5/5/2019 12:33:54 AM ******/
CREATE NONCLUSTERED INDEX [Idx_ZIP_CODES_STATES_DIM_ZIPCODE] ON [dbo].[ZIP_CODES_STATES_DIM]
(
	ZIP_CODES_STATES_ZIPCODE ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO




------------------------------------------------------------


use ReportingDB
Go

DROP TABLE DBO.[SCRIPT_STATUS_FACT]
USE [ReportingDB]
GO

/****** Object:  Table [dbo].[SCRIPT_STATUS_FACT]    Script Date: 5/5/2019 1:02:35 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SCRIPT_STATUS_FACT](
	[SCRIPT_ID] [bigint] NULL,
	[CLIENT_DIM_KEY] [int] NULL,
	[TREATMENT_TYPE_DIM_KEY] [int] NULL,
	[SERVICE_TYPE_DIM_KEY] [int] NULL,
	[PRODUCT_TYPE_DIM_KEY] [int] NULL,
	[REFERRALSTATUS_TYPE_DIM_KEY] [int] NULL,
	[REFERRALSTATUS_TYPE_NAME] [varchar](100) NULL,
	[REFERRAL_SUBSTATUS_TYPE_DIM_KEY] [int] NULL,
	[DATE_OF_INJURY] [date] NULL,
	[CLAIM_NUMBER] [varchar](255) NULL,
	[IS_BID_ACCEPTED] [bit] NULL,
	[BID_SUBMITTED_DATE] [date] NULL,
	[ZIP_CODES_STATES_STATECODE] [varchar](50) NULL,
	[REFERRAL_SUBMITTED_DATE] [date] NULL,
	[BID_EXPIREDATE] [date] NULL,
	[IS_BID_EXPIRED] [bit] NULL
) ON [PRIMARY]
GO



truncate table DBO.[SCRIPT_STATUS_FACT]

INSERT INTO DBO.[SCRIPT_STATUS_FACT]
([SCRIPT_ID], [CLIENT_DIM_KEY], [TREATMENT_TYPE_DIM_KEY], [SERVICE_TYPE_DIM_KEY], [PRODUCT_TYPE_DIM_KEY], [REFERRALSTATUS_TYPE_DIM_KEY], [REFERRALSTATUS_TYPE_NAME], [REFERRAL_SUBSTATUS_TYPE_DIM_KEY], [DATE_OF_INJURY], [CLAIM_NUMBER], [IS_BID_ACCEPTED], [BID_SUBMITTED_DATE], [ZIP_CODES_STATES_STATECODE], [REFERRAL_SUBMITTED_DATE], [BID_EXPIREDATE], [IS_BID_EXPIRED]
)
--script_status_fact
select r.scriptid
,cd.CLIENT_DIM_KEY
,[TREATMENT_TYPE_DIM_KEY]
,[SERVICE_TYPE_DIM_KEY]
,[PRODUCT_TYPE_DIM_KEY]
,rstd.[REFERRALSTATUS_TYPE_DIM_KEY]
,rstd.REFERRALSTATUS_TYPE_NAME
,rsstd.[REFERRAL_SUBSTATUS_TYPE_DIM_KEY]
,r.DateOfInjury
,r.ClaimNumber
,prbd.IsBidAccepted
--,prbd.BidPrice
--,prbd.StandingPrice
--,prbd.distance
,prbd.SubmittedDate as bid_submitted_date
,NULL --zd.ZIP_CODES_STATES_STATECODE
,rtsm.SubmittedDate referral_submitted_date
,rtsm.BidExpireDate
,rtsm.IsBidExpired
from thm.dbo.referral r
join thm.dbo.ReferralTreatmentServiceMap rtsm on rtsm.ReferralId = r.id
join thm.dbo.ReferralTreatmentServiceProviderMap rtsp on rtsp.ReferralTreatmentServiceMapId = rtsm.id
join thm.dbo.[ProviderReferralBidDescision] prbd on prbd.[ReferralTreatmentServiceProviderMapId ] = rtsp.id
join reportingdb.[dbo].[CLIENT_DIM] cd on cd.[CLIENT_GUID] = r.ClientId
join  [THM].[ref].[ReferralStatusType] rst on rst.Id = rtsm.ReferralStatusTypeId
left outer join thm.[ref].[ReferralSubStatusType] rsst on rsst.ReferralStatusTypeId = rst.id
join reportingdb.[dbo].[REFERRALSTATUS_TYPE_DIM] rstd on rstd.[REFERRALSTATUS_TYPE_NAME] = rst.Name
left outer join reportingdb.[dbo].[REFERRAL_SUBSTATUS_TYPE_DIM] rsstd on rsstd.[REFERRAL_SUBSTATUS_TYPE_NAME] = rsst.SubStatusName
join [ReportingDB].[dbo].[TREATMENT_TYPE_DIM] ttd on ttd.[TREATMENT_TYPE_GUID] = rtsm.TreatmentTypeId
join [ReportingDB].[dbo].[SERVICE_TYPE_DIM] std on std.[SERVICE_TYPE_GUID] = rtsm.servicetypeid
join [ReportingDB].[dbo].[PRODUCT_TYPE_DIM] ptd on ptd.[PRODUCT_TYPE_GUID] = rtsm.producttypeid
join thm.[ref].[LookupType] lt on lt.id = '4F3FD818-B969-496D-BD43-9173E889C921'
join thm.dbo.lookup lu on lu.LookupTypeID = lt.id 
--left outer join ReportingDB.[dbo].[ZIP_CODES_STATES_DIM] zd on zd.[ZIP_CODES_STATES_STATECODE] = lu.Description




